name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: yarn global add typescript
    - run: yarn
    - run: yarn build

    # do the lint after build, because build also builds juvenal-lib
    - run: yarn lint:check
    - run: | # the touch is needed so that underscored files work for GitHub Pages
        yarn doc
        touch ./build/.nojekyll
    - run: yarn coverage
      env:
        CI: true

    # update code coverage in codecov.io
    - uses: codecov/codecov-action@v1
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # required, use a github secret for that
        fail_ci_if_error: true              # optional (default=false)

    # publish gh-pages branch
    - name: Deploy gh-pages
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./build/